import asyncio
import mimetypes
import os
import re
import subprocess
import tempfile
from pathlib import Path
from typing import Dict, Iterable, List, Set, Tuple
from urllib.parse import urlparse
from urllib.request import Request, urlopen

VSCO_PLAYWRIGHT_PROFILE_DIR = Path(__file__).resolve().parent.parent / ".auth" / "vsco_playwright_profile"

USER_AGENT = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"
)


def extract_username(url: str) -> str:
    if not url.startswith(("http://", "https://")):
        url = "https://" + url
    match = re.search(r"vsco\.co/([^/?#]+)", url)
    if match:
        return match.group(1).lower()
    raise ValueError("Could not find username in URL. Example: https://vsco.co/username")


def _sanitize_character(character: str) -> str:
    safe = re.sub(r"[^a-zA-Z0-9._ -]+", "_", (character or "Unsorted")).strip()
    return safe or "Unsorted"


def _count_images(folder: Path) -> int:
    exts = {".jpg", ".jpeg", ".png", ".webp", ".gif", ".avif"}
    return sum(1 for p in folder.rglob("*") if p.is_file() and p.suffix.lower() in exts)


def _cookiejar_to_netscape(cookiejar, out_file: Path) -> int:
    lines = [
        "# Netscape HTTP Cookie File",
        "# This file was generated by LoRA Pack UI downloader.",
    ]
    count = 0
    for cookie in cookiejar:
        domain = cookie.domain or ""
        if "vsco" not in domain.lower():
            continue

        include_subdomains = "TRUE" if domain.startswith(".") else "FALSE"
        secure = "TRUE" if bool(cookie.secure) else "FALSE"
        expiry = str(int(cookie.expires or 0))
        path = cookie.path or "/"
        name = cookie.name or ""
        value = cookie.value or ""

        lines.append("\t".join([domain, include_subdomains, path, secure, expiry, name, value]))
        count += 1

    out_file.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return count


def _export_browser_cookies_to_netscape(browser: str) -> Tuple[Path | None, str]:
    try:
        import browser_cookie3
    except Exception:
        return None, "browser_cookie3 is not installed"

    try:
        if browser == "chrome":
            jar = browser_cookie3.chrome(domain_name="vsco.co")
        elif browser == "edge":
            jar = browser_cookie3.edge(domain_name="vsco.co")
        else:
            return None, f"Unsupported browser '{browser}'"

        fd, temp_path = tempfile.mkstemp(prefix=f"vsco_{browser}_", suffix=".cookies.txt")
        os.close(fd)
        out = Path(temp_path)
        count = _cookiejar_to_netscape(jar, out)
        if count <= 0:
            out.unlink(missing_ok=True)
            return None, f"No VSCO cookies found in {browser}"
        return out, f"Exported {count} VSCO cookies from {browser}"
    except Exception as exc:
        return None, f"Could not export {browser} cookies: {exc}"


def _run_gallery_dl(gallery_url: str, base_dir: Path, archive: Path, manual_cookie_path: str | None = None) -> Tuple[bool, str]:
    base_cmd = [
        "gallery-dl",
        "--directory",
        str(base_dir),
        "--download-archive",
        str(archive),
    ]
    if os.environ.get("VSCO_WRITE_METADATA", "0").strip() == "1":
        base_cmd.append("--write-metadata")

    cookie_files: List[Path] = []
    preflight_notes: List[str] = []
    cookie_file_attempts: List[Tuple[str, List[str]]] = []

    manual_cookie_path = (manual_cookie_path or os.environ.get("VSCO_COOKIES_FILE", "")).strip()
    if manual_cookie_path:
        manual_file = Path(manual_cookie_path)
        if manual_file.exists() and manual_file.is_file():
            cookie_file_attempts.append(("cookies-file:manual", ["--cookies", str(manual_file)]))
            preflight_notes.append(f"Using VSCO_COOKIES_FILE={manual_file}")
        else:
            preflight_notes.append(f"VSCO_COOKIES_FILE not found: {manual_cookie_path}")

    for browser in ("chrome", "edge"):
        cookie_file, note = _export_browser_cookies_to_netscape(browser)
        preflight_notes.append(note)
        if cookie_file is not None:
            cookie_files.append(cookie_file)
            cookie_file_attempts.append((f"cookies-file:{browser}", ["--cookies", str(cookie_file)]))

    attempts = cookie_file_attempts + [
        ("cookies:chrome", ["--cookies-from-browser", "chrome"]),
        ("cookies:edge", ["--cookies-from-browser", "edge"]),
        ("cookies:chrome:Default", ["--cookies-from-browser", "chrome:Default"]),
        ("cookies:edge:Default", ["--cookies-from-browser", "edge:Default"]),
        ("no-cookies", []),
    ]

    env = dict(os.environ)
    env["PYTHONIOENCODING"] = "utf-8"
    last_error = "gallery-dl failed"

    try:
        for label, cookie_args in attempts:
            cmd = base_cmd + cookie_args + [gallery_url]
            try:
                print(f"Trying gallery-dl with {label}...")
                proc = subprocess.Popen(
                    cmd,
                    stdout=subprocess.PIPE,
                    stderr=subprocess.PIPE,
                    text=True,
                    env=env,
                )
                _, stderr = proc.communicate()
                if proc.returncode == 0:
                    count = _count_images(base_dir)
                    note_tail = f" Cookie prep: {'; '.join(preflight_notes)}" if preflight_notes else ""
                    return True, f"gallery-dl succeeded with {label}. Files currently in folder: {count}.{note_tail}"
                err_text = (stderr or "gallery-dl failed").strip()
                last_error = f"[{label}] {err_text}"[:1600]
            except FileNotFoundError:
                return False, "gallery-dl is not installed or not on PATH."
            except Exception as exc:
                last_error = f"[{label}] {exc}"[:1600]
    finally:
        for p in cookie_files:
            p.unlink(missing_ok=True)

    if preflight_notes:
        last_error = f"{last_error} | Cookie prep: {'; '.join(preflight_notes)}"
    return False, last_error


def _parse_srcset(srcset: str) -> List[str]:
    urls: List[str] = []
    for chunk in (srcset or "").split(","):
        token = chunk.strip().split(" ")[0].strip()
        if token.startswith("http"):
            urls.append(token)
    return urls


def _extract_image_urls_from_text(text: str) -> Set[str]:
    pattern = re.compile(
        r"https://[^\s\"'<>]*vsco[^\s\"'<>]*\.(?:jpg|jpeg|png|webp|avif)(?:\?[^\s\"'<>]*)?",
        re.IGNORECASE,
    )
    return set(pattern.findall(text or ""))


def _filter_vsco_image_urls(urls: Iterable[str]) -> List[str]:
    filtered = []
    for raw in sorted(set(urls)):
        parsed = urlparse(raw)
        host = parsed.netloc.lower()
        if "vsco" not in host:
            continue
        if not parsed.path.lower().endswith((".jpg", ".jpeg", ".png", ".webp", ".avif")):
            continue
        filtered.append(raw)
    return filtered


def _collect_vsco_urls_playwright(gallery_url: str, headless: bool = True) -> Tuple[List[str], str]:
    mode = os.environ.get("VSCO_ENABLE_PLAYWRIGHT", "auto").strip().lower()
    if mode in ("0", "false", "off"):
        return [], "Playwright fallback disabled by VSCO_ENABLE_PLAYWRIGHT"

    if os.name == "nt":
        try:
            asyncio.set_event_loop_policy(asyncio.WindowsProactorEventLoopPolicy())
        except Exception:
            pass

    try:
        from playwright.sync_api import sync_playwright
    except Exception:
        return [], "Playwright package is not installed"

    urls: Set[str] = set()

    try:
        VSCO_PLAYWRIGHT_PROFILE_DIR.mkdir(parents=True, exist_ok=True)
        with sync_playwright() as p:
            context = p.chromium.launch_persistent_context(
                user_data_dir=str(VSCO_PLAYWRIGHT_PROFILE_DIR),
                headless=headless,
                user_agent=USER_AGENT,
                locale="en-US",
                viewport={"width": 1280, "height": 1800},
            )
            page = context.pages[0] if context.pages else context.new_page()

            def add_url(candidate: str):
                if candidate and candidate.startswith("http"):
                    urls.add(candidate)

            def on_response(resp):
                add_url(resp.url)
                try:
                    ctype = str(resp.headers.get("content-type", "")).lower()
                    if "json" in ctype:
                        txt = resp.text()
                        for u in _extract_image_urls_from_text(txt):
                            add_url(u)
                except Exception:
                    pass

            page.on("request", lambda req: add_url(req.url))
            page.on("response", on_response)

            goto_resp = page.goto(gallery_url, wait_until="domcontentloaded", timeout=45000)
            try:
                status = int(goto_resp.status) if goto_resp else 0
            except Exception:
                status = 0
            if status >= 400:
                context.close()
                return [], f"Playwright HTTP {status} while opening gallery"

            last_height = 0
            stable_rounds = 0
            for _ in range(30):
                page.mouse.wheel(0, 7000)
                page.wait_for_timeout(400)
                height = int(page.evaluate("document.body.scrollHeight"))
                if height <= last_height:
                    stable_rounds += 1
                else:
                    stable_rounds = 0
                last_height = height
                if stable_rounds >= 4:
                    break

            img_data = page.evaluate(
                """() => Array.from(document.querySelectorAll(\"img\")).map((img) => ({
                    src: img.getAttribute(\"src\") || \"\",
                    currentSrc: img.currentSrc || \"\",
                    srcset: img.getAttribute(\"srcset\") || \"\",
                    dataSrc: img.getAttribute(\"data-src\") || \"\",
                    dataSrcset: img.getAttribute(\"data-srcset\") || \"\"
                }))"""
            )

            for item in img_data:
                for key in ("src", "currentSrc", "dataSrc"):
                    value = (item.get(key) or "").strip()
                    if value.startswith("http"):
                        urls.add(value)
                for key in ("srcset", "dataSrcset"):
                    urls.update(_parse_srcset(item.get(key) or ""))

            context.close()
    except Exception as exc:
        return [], f"Playwright runtime failed: {exc}"

    filtered = _filter_vsco_image_urls(urls)
    if not filtered:
        return [], "Playwright ran but found no VSCO image URLs"
    return filtered, ""


def _collect_vsco_urls_html(gallery_url: str) -> List[str]:
    headers = {
        "User-Agent": USER_AGENT,
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "Accept-Language": "en-US,en;q=0.9",
        "Referer": "https://vsco.co/",
    }
    try:
        req = Request(gallery_url, headers=headers)
        with urlopen(req, timeout=25) as resp:
            html = resp.read().decode("utf-8", errors="ignore")
    except Exception:
        return []

    return _filter_vsco_image_urls(_extract_image_urls_from_text(html))



def _download_urls_with_playwright(urls: Iterable[str], out_dir: Path) -> Tuple[int, int, str]:
    mode = os.environ.get("VSCO_ENABLE_PLAYWRIGHT", "auto").strip().lower()
    if mode in ("0", "false", "off"):
        return 0, 0, "Playwright fallback disabled by VSCO_ENABLE_PLAYWRIGHT"

    if os.name == "nt":
        try:
            asyncio.set_event_loop_policy(asyncio.WindowsProactorEventLoopPolicy())
        except Exception:
            pass

    try:
        from playwright.sync_api import sync_playwright
    except Exception:
        return 0, 0, "Playwright package is not installed"

    normalized_urls = [u for u in _filter_vsco_image_urls(urls)]
    if not normalized_urls:
        return 0, 0, "No VSCO image URLs to download"

    downloaded = 0
    skipped = 0
    last_error = ""

    try:
        VSCO_PLAYWRIGHT_PROFILE_DIR.mkdir(parents=True, exist_ok=True)
        with sync_playwright() as p:
            context = p.chromium.launch_persistent_context(
                user_data_dir=str(VSCO_PLAYWRIGHT_PROFILE_DIR),
                headless=True,
                user_agent=USER_AGENT,
                locale="en-US",
                viewport={"width": 1280, "height": 1000},
            )
            reqctx = context.request

            for idx, image_url in enumerate(normalized_urls, start=1):
                name = _unique_name_from_url(image_url, idx)
                target = out_dir / name
                if target.exists():
                    skipped += 1
                    continue

                try:
                    resp = reqctx.get(
                        image_url,
                        timeout=35000,
                        headers={
                            "User-Agent": USER_AGENT,
                            "Accept": "image/avif,image/webp,image/apng,image/*,*/*;q=0.8",
                            "Accept-Language": "en-US,en;q=0.9",
                            "Referer": "https://vsco.co/",
                            "Origin": "https://vsco.co",
                        },
                    )
                    if not resp.ok:
                        last_error = f"HTTP {resp.status} for {image_url}"
                        continue
                    payload = resp.body()
                    if not payload:
                        last_error = f"Empty response for {image_url}"
                        continue

                    ctype = str(resp.headers.get("content-type", "")).split(";")[0].strip().lower()
                    if ctype and ctype.startswith("image/"):
                        guessed_ext = mimetypes.guess_extension(ctype) or ""
                        if guessed_ext and target.suffix.lower() not in (".jpg", ".jpeg", ".png", ".webp", ".avif"):
                            target = target.with_suffix(guessed_ext)

                    target.write_bytes(payload)
                    downloaded += 1
                except Exception as exc:
                    last_error = str(exc)

            context.close()
    except Exception as exc:
        return downloaded, skipped, f"Playwright download runtime failed: {exc}"

    return downloaded, skipped, last_error
def _unique_name_from_url(url: str, idx: int) -> str:
    parsed = urlparse(url)
    parts = [p for p in parsed.path.split("/") if p]
    filename = parts[-1] if parts else f"img_{idx:05d}.jpg"
    filename = filename.split("?")[0].split("#")[0]
    media_id = parts[-2] if len(parts) >= 2 else ""
    base_name = re.sub(r"[^a-zA-Z0-9._-]+", "_", filename) or f"img_{idx:05d}.jpg"
    if media_id and media_id not in base_name:
        base_name = f"{media_id}_{base_name}"
    return base_name


def _download_urls(urls: Iterable[str], out_dir: Path) -> Tuple[int, int, str]:
    headers = {
        "User-Agent": USER_AGENT,
        "Accept": "image/avif,image/webp,image/apng,image/*,*/*;q=0.8",
        "Accept-Language": "en-US,en;q=0.9",
        "Referer": "https://vsco.co/",
        "Origin": "https://vsco.co",
    }

    downloaded = 0
    skipped = 0
    last_error = ""

    for idx, image_url in enumerate(urls, start=1):
        name = _unique_name_from_url(image_url, idx)
        target = out_dir / name
        if target.exists():
            skipped += 1
            continue

        try:
            req = Request(image_url, headers=headers)
            with urlopen(req, timeout=35) as resp:
                status = int(getattr(resp, "status", 200))
                if status >= 400:
                    last_error = f"HTTP {status} for {image_url}"
                    continue
                payload = resp.read()
                if not payload:
                    last_error = f"Empty response for {image_url}"
                    continue

                ctype = str(resp.headers.get("Content-Type", "")).split(";")[0].strip().lower()
                if ctype and ctype.startswith("image/"):
                    guessed_ext = mimetypes.guess_extension(ctype) or ""
                    if guessed_ext and target.suffix.lower() not in (".jpg", ".jpeg", ".png", ".webp", ".avif"):
                        target = target.with_suffix(guessed_ext)

            target.write_bytes(payload)
            downloaded += 1
        except Exception as exc:
            last_error = str(exc)

    return downloaded, skipped, last_error


def download_vsco(url: str, character: str = "Unsorted", cookies_file: str | None = None) -> Dict:
    username = None
    try:
        username = extract_username(url)
        gallery_url = f"https://vsco.co/{username}/gallery"
        safe_character = _sanitize_character(character)
        base_dir = Path(__file__).parent.parent / "downloads" / safe_character / f"vsco_{username}"
        base_dir.mkdir(parents=True, exist_ok=True)
        archive = base_dir.parent / f"vsco_{username}-archive.txt"

        ok, gallery_msg = _run_gallery_dl(gallery_url, base_dir, archive, cookies_file)
        current_files = _count_images(base_dir)
        if ok and current_files > 0:
            msg = f"Done via gallery-dl. Downloaded to {base_dir}. Total files currently in folder: {current_files}"
            return {
                "status": "success",
                "username": username,
                "folder": str(base_dir.absolute()),
                "message": msg,
            }

        source = "Playwright headless"
        image_urls, play_err = _collect_vsco_urls_playwright(gallery_url, headless=True)
        if not image_urls:
            source = "Playwright headed"
            image_urls, headful_err = _collect_vsco_urls_playwright(gallery_url, headless=False)
            if not image_urls and headful_err:
                play_err = f"{play_err}; {headful_err}" if play_err else headful_err
        if not image_urls:
            source = "HTML fallback"
            image_urls = _collect_vsco_urls_html(gallery_url)

        if image_urls:
            downloaded, skipped, dl_error = _download_urls_with_playwright(image_urls, base_dir)
            if downloaded == 0 and skipped == 0:
                plain_downloaded, plain_skipped, plain_error = _download_urls(image_urls, base_dir)
                downloaded += plain_downloaded
                skipped += plain_skipped
                dl_error = plain_error or dl_error
            current_files = _count_images(base_dir)
            if downloaded > 0 or current_files > 0:
                msg = (
                    f"Done via {source}. New: {downloaded}, skipped existing: {skipped}. "
                    f"Total files currently in folder: {current_files}"
                )
                return {
                    "status": "success",
                    "username": username,
                    "folder": str(base_dir.absolute()),
                    "message": msg,
                }

            details = dl_error or "No image URLs were downloadable from fallback collection."
            raise RuntimeError(f"{gallery_msg} | {source} failed: {details}")

        raise RuntimeError(
            f"{gallery_msg} | {play_err or 'Playwright found no URLs'} | "
            "No image URLs found from Playwright or HTML fallback. "
            "Install Playwright + Chromium, or install browser_cookie3 to improve cookie export fallback."
        )
    except Exception as exc:
        error_msg = f"error: {exc}"
        return {
            "status": "error",
            "message": error_msg,
            "username": username,
        }



